### ISSUE TITLE
Journal of Limnology missing from list

### ISSUE THREAD

**Issue by EsterME** [jsta/limnopapers#91]
Dear authors
The Journal of Limnology, a nearly 80 years old journal centred on limnology is missing from the feed. 
https://www.jlimnol.it/index.php/jlimnol/issue/view/73
Please consider adding it.
Kind regards
Journal of Limnology
Twitter: @j_limnology

**Comment by jsta** [comment]
This feed aggregates and filters individual already existing RSS feeds for specific journals. I don't see an RSS feed listed on the Journal of Limnology site. Do you know if they have an RSS feed?
